server:
  port: 8000
# DataSource Config
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://116.205.231.172:3306/spring_boot?serverTimezone=GMT%2B8
    username: root
    password: Nuonuoo201314.
    driver-class-name: com.mysql.cj.jdbc.Driver

#注册中心
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/

